# Generated by Django 3.1.7 on 2021-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210423_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroBebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quant_litro', models.IntegerField()),
            ],
        ),
    ]
