# Generated by Django 3.1.7 on 2021-04-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_cadastrobebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroHamburgue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quant_kg', models.IntegerField()),
            ],
        ),
    ]
