# Generated by Django 3.1.7 on 2021-04-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_cadastrohamburgue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='CadastroBebida',
            new_name='Bebida',
        ),
        migrations.RenameModel(
            old_name='CadastroHamburgue',
            new_name='Hamburgue',
        ),
        migrations.RenameField(
            model_name='hamburgue',
            old_name='quant_kg',
            new_name='quantidade',
        ),
    ]
