# Generated by Django 3.1.7 on 2021-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210424_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroatendente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=128, verbose_name='Gênero'),
        ),
    ]
