# Generated by Django 3.1.7 on 2021-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20210424_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroLocalDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritar', models.CharField(choices=[('C', 'Casa'), ('T', 'Trabalho')], max_length=128, verbose_name='Favoritar como')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município')),
                ('uf', models.CharField(choices=[('C', 'Casa'), ('T', 'Trabalho')], max_length=128, verbose_name='UF')),
            ],
        ),
    ]
