# Generated by Django 3.1.7 on 2021-04-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_pastel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebida',
            old_name='quant_litro',
            new_name='tamanho',
        ),
        migrations.RenameField(
            model_name='hamburgue',
            old_name='quantidade',
            new_name='tamanho',
        ),
        migrations.RenameField(
            model_name='passaporte',
            old_name='quantidade',
            new_name='tamanho',
        ),
        migrations.RenameField(
            model_name='pastel',
            old_name='quantidade',
            new_name='tamanho',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='quantidade',
            new_name='tamanho',
        ),
    ]
