# Generated by Django 3.1.7 on 2021-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_auto_20210424_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hamburgue',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passaporte',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
    ]
