# Generated by Django 3.1.7 on 2021-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_auto_20210424_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endere',
            field=models.CharField(max_length=20, null=True, verbose_name='Endereço completo'),
        ),
    ]
