# Generated by Django 3.1.7 on 2021-04-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_auto_20210424_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='categoria_venda',
            field=models.ManyToManyField(limit_choices_to='Passaporte', related_name='Hamburguer', related_query_name='Pizza', to='vendas.Bebida'),
        ),
    ]
