# Generated by Django 3.1.7 on 2021-04-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_auto_20210424_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email_cliente',
            new_name='email_Cliente',
        ),
    ]
