# Generated by Django 3.1.7 on 2021-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_auto_20210424_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_Cliente',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
