# Generated by Django 3.1.7 on 2021-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_auto_20210424_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePegueLeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endere', models.CharField(max_length=20, null=True, verbose_name='Endereço completo')),
                ('cidade', models.CharField(max_length=20, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=20, null=True, verbose_name='CEP')),
                ('email_Cliente', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
            ],
        ),
    ]
