# Generated by Django 3.1.7 on 2021-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_auto_20210424_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='categoria_venda',
            field=models.ManyToManyField(related_name='Hamburgue', to='vendas.Bebida'),
        ),
    ]
