# Generated by Django 3.1.7 on 2021-04-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_remove_cadastrorestaurante_categoria_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorsRelacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.bebida')),
                ('hamburgue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.hamburgue')),
                ('passaporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.passaporte')),
                ('pastel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.pastel')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='cadastrorestaurante',
            name='categoria',
            field=models.ManyToManyField(to='vendas.CreatorsRelacao'),
        ),
    ]
