# Generated by Django 3.1.7 on 2021-04-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0022_auto_20210425_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='produtos',
            new_name='produtos_pedidos',
        ),
    ]
