# Generated by Django 3.1.7 on 2021-04-25 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0024_auto_20210425_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.IntegerField()),
                ('entrega_concluida', models.BooleanField()),
                ('atendente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cadastroatendente', verbose_name='Atendente')),
                ('bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.bebida')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cliente', verbose_name='Cliente')),
                ('hamburgue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.hamburgue')),
                ('passaporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.passaporte')),
                ('pastel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.pastel')),
                ('pizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.pizza')),
            ],
        ),
    ]
