# Generated by Django 3.1.7 on 2021-04-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0027_auto_20210425_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=8, verbose_name='CPF'),
        ),
    ]
