# Generated by Django 3.1.7 on 2021-04-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0031_auto_20210425_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormasPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.BooleanField()),
                ('cartaodecredito', models.BooleanField()),
                ('criptomoeda', models.BooleanField()),
                ('aplicativo_pagamento', models.BooleanField()),
                ('pontos_pagamento', models.BooleanField()),
                ('nome_restaurante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cadastrorestaurante', verbose_name='Nome do Restaurante')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='entregaproduto',
            name='cliente',
            field=models.ManyToManyField(to='vendas.Cliente'),
        ),
    ]
