# Generated by Django 3.1.7 on 2021-04-26 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0033_auto_20210425_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaproduto',
            name='cliente',
        ),
        migrations.AddField(
            model_name='entregaproduto',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vendas.cliente'),
        ),
    ]
