# Generated by Django 3.1.7 on 2021-04-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0035_auto_20210425_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitacaoProdutosProducao',
            new_name='SolicitacaoProduto',
        ),
    ]
