# Generated by Django 3.1.7 on 2021-05-31 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroAtendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Atendente')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome do Atendente')),
                ('email_atendente', models.EmailField(max_length=254, null=True, verbose_name='E-mail Atendente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF do Atendente')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=128, verbose_name='Gênero')),
                ('possui_comorbidade', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação Comorbidade')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, default=1, verbose_name='Data de nascimento')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('salvar_foto_perfil', models.FileField(upload_to='foto_atendente/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço do Restaurante')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ramo_atuacao', models.CharField(max_length=128, verbose_name='Ramo de Atuação')),
                ('email_do_fornecedor', models.EmailField(max_length=254, null=True, verbose_name='E-mail do Fornecedor')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroLocalDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritar', models.CharField(choices=[('C', 'Casa'), ('T', 'Trabalho'), ('P', 'Pegue e leve')], max_length=128, verbose_name='Favoritar como')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=50, verbose_name='CEP')),
                ('bairro', models.CharField(blank=True, max_length=50, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=50, verbose_name='Município')),
                ('uf', models.CharField(blank=True, choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federa', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', ' PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', ' SE'), ('Tocantins', 'TO')], max_length=128, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroRestaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(max_length=255, verbose_name='Nome do Restaurante')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço do Restaurante')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('email_da_empresa', models.EmailField(max_length=254, null=True, verbose_name='E-mail da Empresa')),
                ('ramo', models.CharField(choices=[('B', 'Bebida'), ('H', 'Hamburguer'), ('Pi', 'Pizza'), ('Pa', 'Passaporte'), ('Pas', 'Pastel')], default=5, max_length=128, verbose_name='Ramo da empresa')),
                ('telefone', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endere', models.CharField(max_length=128, null=True, verbose_name='Endereço Completo')),
                ('data_nascimento', models.DateField(blank=True, default=1, verbose_name='Data de nascimento')),
                ('cidade', models.CharField(max_length=50, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
                ('email_cliente', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='ClientePegueLeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(blank=True, default=1, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endere', models.CharField(max_length=20, null=True, verbose_name='Endereço completo')),
                ('cidade', models.CharField(max_length=20, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=20, null=True, verbose_name='CEP')),
                ('email_Cliente', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='FazerPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('bebida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.bebida')),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Venda')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da venda')),
                ('data_hora_venda', models.DateTimeField(blank=True, verbose_name='Data e Hora da venda')),
                ('numero_venda', models.IntegerField(verbose_name='Número da Venda')),
                ('comprovante_venda', models.FileField(upload_to='comprovante_venda/', verbose_name='Comprovante de Venda')),
                ('venda_concluida', models.BooleanField(default=True)),
                ('qtd_itens', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens Vendidos')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('novo_item', models.IntegerField()),
                ('excluido', models.BooleanField(blank=True, default=False)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente', verbose_name='Cliente')),
                ('descricao_pedido', models.ManyToManyField(to='dliver.FazerPedido', verbose_name='Produtos Pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCupom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cupom', models.CharField(max_length=255, verbose_name='Título do Cupom')),
                ('codigo_promocional', models.CharField(max_length=255, verbose_name='Código Promocional')),
                ('categoria_produto_cupons', models.CharField(max_length=255, verbose_name='Categoria de Cupom')),
                ('validade_cupom', models.DateField(verbose_name='Validade do Cupom')),
                ('parceiro_cupom', models.CharField(max_length=255, verbose_name='Nome do Parceiro')),
                ('link_cupom', models.URLField(verbose_name='Link')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente')),
                ('nome_empresa_cupom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrorestaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('tamanho', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('quantidade', models.CharField(max_length=10, verbose_name='Quantidade')),
                ('nacionalidade_do_produto', models.CharField(max_length=10, verbose_name='Nacionalidade do Produto')),
                ('observacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Observação')),
                ('fornecedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrofornecedor', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='FormasPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.CharField(max_length=255, verbose_name='Chave Pix')),
                ('cartoes_de_credito', models.CharField(max_length=255, verbose_name='Cartões de Crédito')),
                ('cartoes_de_debito', models.CharField(max_length=255, verbose_name='Cartões de Débito')),
                ('criptomoeda', models.CharField(max_length=255, verbose_name='Criptomoeda')),
                ('app_pagamento', models.CharField(max_length=255, verbose_name='Aplicativo de Pagamento')),
                ('app_pontos', models.CharField(max_length=255, verbose_name='Aplicativo de Pontos')),
                ('nome_restaurante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrorestaurante', verbose_name='Nome do Restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='hamburguer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.hamburguer'),
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='local_de_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrolocaldeentrega'),
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='nome_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente'),
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='passaporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.passaporte'),
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='pastel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.pastel'),
        ),
        migrations.AddField(
            model_name='fazerpedido',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.pizza'),
        ),
        migrations.CreateModel(
            name='EntregaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.IntegerField(default=False, verbose_name='Número da entrega')),
                ('momento_pagamento', models.CharField(blank=True, choices=[('ENTREGA', 'ENTREGA'), ('APP', 'APP')], max_length=128, verbose_name='Local de pagamento')),
                ('entrega_concluida', models.BooleanField(blank=True, default=False)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('descricao_pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.fazerpedido')),
                ('nome_antendente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastroatendente', verbose_name='Atendente')),
                ('nome_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cadastrofornecedor',
            name='empresa_fornecida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrorestaurante', verbose_name='Empresa Fornecida'),
        ),
    ]
