# Generated by Django 3.1.7 on 2021-04-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0002_venda_exemplo_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email_cliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='email_cliente',
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprovante_venda',
            field=models.FileField(upload_to='comprovante_venda/', verbose_name='Comprovante de Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.IntegerField(verbose_name='Número da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='qtd_itens',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Itens Vendidos'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='dliver.Produto'),
        ),
    ]
