# Generated by Django 3.1.7 on 2021-05-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0002_auto_20210531_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade do produto'),
        ),
    ]
