# Generated by Django 3.1.7 on 2021-06-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0004_auto_20210531_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='comprovante_venda',
            field=models.FileField(upload_to='comprovante_venda/', verbose_name='Comprovante da Venda'),
        ),
    ]
