# Generated by Django 3.1.7 on 2021-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0004_auto_20210424_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroatendente',
            name='email_atendente',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail Atendente'),
        ),
        migrations.AlterField(
            model_name='cadastroatendente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=128),
        ),
        migrations.AlterField(
            model_name='cadastroatendente',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação_Comorbidade'),
        ),
        migrations.AlterField(
            model_name='cadastroatendente',
            name='possui_comorbidade',
            field=models.BooleanField(default=False),
        ),
    ]
