# Generated by Django 3.1.7 on 2021-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0005_auto_20210424_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroatendente',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação Comorbidade'),
        ),
    ]
