# Generated by Django 3.1.7 on 2021-06-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0006_auto_20210531_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrofornecedor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='telefone',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientepegueleve',
            name='tel',
            field=models.CharField(max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
