# Generated by Django 3.1.7 on 2021-06-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0007_auto_20210531_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazerpedido',
            name='local_de_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrolocaldeentrega', verbose_name='Local de entrega'),
        ),
        migrations.AlterField(
            model_name='fazerpedido',
            name='nome_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cliente', verbose_name='Nome do cliente'),
        ),
    ]
