# Generated by Django 3.1.7 on 2021-06-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0008_auto_20210601_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocupom',
            name='nome_empresa_cupom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.cadastrorestaurante', verbose_name='Cupom da Empresa'),
        ),
    ]
