# Generated by Django 3.1.7 on 2021-04-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0010_auto_20210424_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePegueLeve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endere', models.CharField(max_length=20, null=True, verbose_name='Endereço completo')),
                ('cidade', models.CharField(max_length=20, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=20, null=True, verbose_name='CEP')),
                ('email_Cliente', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Hamburgue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=255)),
                ('tamanho', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_Cliente',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endere',
            field=models.CharField(max_length=20, null=True, verbose_name='Endereço completo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tel',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='CadastroRestaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(max_length=255, verbose_name='Nome do Restaurante')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço do Restaurante')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('email_da_empresa', models.EmailField(max_length=254, null=True, verbose_name='E-mail da Empresa')),
                ('categoria_venda', models.ManyToManyField(default=1, limit_choices_to='Passaporte', related_name='Hamburguer', related_query_name='Pizza', to='dliver.Bebida', verbose_name='Cliente')),
            ],
        ),
    ]
