# Generated by Django 3.1.7 on 2021-04-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0011_auto_20210424_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='categoria_venda',
            field=models.ManyToManyField(default=1, limit_choices_to='Passaporte', related_name='Hamburguer', related_query_name='Pizza', to='dliver.Bebida', verbose_name='Categoria de venda'),
        ),
    ]
