# Generated by Django 3.1.7 on 2021-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0013_auto_20210424_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='categoria_venda',
            field=models.ManyToManyField(to='dliver.Bebida'),
        ),
    ]
