# Generated by Django 3.1.7 on 2021-04-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0017_auto_20210425_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatorsRelacao',
            new_name='CategoriasRelacao',
        ),
    ]
