# Generated by Django 3.1.7 on 2021-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0018_auto_20210425_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrorestaurante',
            name='categoria',
        ),
        migrations.AddField(
            model_name='cadastrorestaurante',
            name='ramo',
            field=models.CharField(choices=[('B', 'Bebida'), ('H', 'Hamburgue'), ('Pi', 'Pizza'), ('Pa', 'Passaporte'), ('Pas', 'Pastel')], default=5, max_length=128, verbose_name='Ramo da empresa'),
        ),
    ]
