# Generated by Django 3.1.7 on 2021-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0019_auto_20210425_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='dliver.CategoriasRelacao'),
        ),
    ]
