# Generated by Django 3.1.7 on 2021-04-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0020_auto_20210425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriasrelacao',
            name='bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.bebida'),
        ),
        migrations.AlterField(
            model_name='categoriasrelacao',
            name='hamburgue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.hamburgue'),
        ),
        migrations.AlterField(
            model_name='categoriasrelacao',
            name='passaporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.passaporte'),
        ),
        migrations.AlterField(
            model_name='categoriasrelacao',
            name='pastel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.pastel'),
        ),
        migrations.AlterField(
            model_name='categoriasrelacao',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.pizza'),
        ),
    ]
