# Generated by Django 3.1.7 on 2021-04-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0023_auto_20210425_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasRelacao',
            new_name='SolicitacaoRetiradaEstoque',
        ),
    ]
