# Generated by Django 3.1.7 on 2021-04-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0026_auto_20210425_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListaProdutosPedidos',
            new_name='ListaProdutos',
        ),
    ]
