# Generated by Django 3.1.7 on 2021-04-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0034_auto_20210425_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListaProdutos',
            new_name='SolicitacaoProdutosProducao',
        ),
    ]
