# Generated by Django 3.1.7 on 2021-04-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0036_auto_20210425_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaproduto',
            name='produtos_pedidos_vendas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.venda', verbose_name='Confirmação de Entrega'),
        ),
    ]
