# Generated by Django 3.1.7 on 2021-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0037_auto_20210425_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamburgue',
            new_name='Hamburguer',
        ),
        migrations.RenameField(
            model_name='solicitacaoproduto',
            old_name='hamburgue',
            new_name='hamburguer',
        ),
        migrations.AlterField(
            model_name='cadastrorestaurante',
            name='ramo',
            field=models.CharField(choices=[('B', 'Bebida'), ('H', 'Hamburguer'), ('Pi', 'Pizza'), ('Pa', 'Passaporte'), ('Pas', 'Pastel')], default=5, max_length=128, verbose_name='Ramo da empresa'),
        ),
    ]
