# Generated by Django 3.1.7 on 2021-05-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0039_auto_20210505_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produtos_pedidos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.solicitacaoproduto', verbose_name='Produtos Pedidos'),
        ),
    ]
