# Generated by Django 3.1.7 on 2021-05-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0043_auto_20210505_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tamanho', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CadastroLocalDeEntrega',
        ),
        migrations.RenameField(
            model_name='entregaproduto',
            old_name='antendente',
            new_name='nome_antendente',
        ),
        migrations.RenameField(
            model_name='entregaproduto',
            old_name='cliente',
            new_name='nome_cliente',
        ),
        migrations.AddField(
            model_name='entregaproduto',
            name='numero_entrega',
            field=models.IntegerField(default=False, verbose_name='Número da entrega'),
        ),
        migrations.AddField(
            model_name='entregaproduto',
            name='pagamento_na_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entregaproduto',
            name='produtos_entregues',
            field=models.BooleanField(default=False),
        ),
    ]
