# Generated by Django 3.1.7 on 2021-05-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0044_auto_20210513_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos_pedidos',
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos_pedidos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.solicitacaoproduto', verbose_name='Produtos Pedidos'),
        ),
    ]
