# Generated by Django 3.1.7 on 2021-05-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0047_auto_20210513_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produtos_pedidos',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dliver.solicitacaoproduto', verbose_name='Produtos Pedidos'),
        ),
    ]
