# Generated by Django 3.1.7 on 2021-05-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dliver', '0048_auto_20210513_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos_pedidos',
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos_pedidos',
            field=models.ManyToManyField(to='dliver.SolicitacaoProduto', verbose_name='Produtos Pedidos'),
        ),
    ]
